repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
        # Run the linter.
        -   id: ruff
            args: [ --fix ]
            stages: [pre-commit]
        # Run the formatter.
        -   id: ruff-format
            stages: [pre-commit]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
        -   id: check-yaml
            stages: [pre-commit]
        -   id: end-of-file-fixer
            stages: [pre-commit]
        -   id: trailing-whitespace
            stages: [pre-commit]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'
    hooks:
    -   id: mypy
        stages: [pre-commit]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
    -   id: markdownlint
        stages: [pre-commit]
